### ISSUE TITLE
TravisCI beüzemelése

### ISSUE THREAD

**Issue by fabledpig** [BME-MIT-IET/1505-iet-2019#1]
Continuous Integration beüzemelése.

**Comment by Vikesz12** [comment]
Először a Travis oldalán bekapcsoltam a projektehez a CI -t
![image](https://user-images.githubusercontent.com/24491701/57289594-f568eb80-70bb-11e9-9795-16836eec4b55.png)

**Comment by Vikesz12** [comment]
Utána az első build nem sikerült mert elfelejtettem  commitolni a változtatásokat a yml fájlban.
![image](https://user-images.githubusercontent.com/24491701/57289835-6dcfac80-70bc-11e9-9a06-937606e15996.png)
Miután ezt kijavítottám már fordult is minden build. Ezen kivül még egy badget hozzá adtam a README.md - hez.
