### ISSUE TITLE
Tesztek kódlefedettségének mérése

### ISSUE THREAD

**Issue by Vikesz12** [BME-MIT-IET/1505-iet-2019#6]
A Codecove.io segítségével tesztek kódlefedettségének mérése.

**Comment by fabledpig** [comment]
Először regisztráltam a projektet a [codecov.io](codecov.io) oldalon.
Ahhoz, hogy egy **C** programban kódlefedettséget tudjak mérni a következő flag-eket kellett beállítanom: `-O0 -coverage`, továbbá linkelni kellett a _gcov_ könvytárat a projekthez. Ezt a következő fájlok szerkesztésével értem el:
```
kazmath/CMakeLists.txt
tests/CMakeLists.txt
```
A projekt fordítása utána futtattam a teszteket:
`make test`

Létrehoztam a coverage reportot az alábbi parancsokkal (a _build_ mappából kiadva):
```
cd kazmath/CMakeFiles/kazmath.dir
lcov --capture --directory . --output-file coverage.info
```
A jelentést pedig a `bash <(curl -s https://codecov.io/bash) -f coverage.info` paranccsal feltöltöttem a Codecov-ra.

A módszer tesztelése után a lépéseket integráltam a _TravisCI_ lépései közé: 674e035, 7c6372f

**Comment by fabledpig** [comment]
![image](https://user-images.githubusercontent.com/3868156/57471587-c73a0600-728b-11e9-9557-43b6e8ab3c75.png)
