### ISSUE TITLE
Unit tesztek készítése

### ISSUE THREAD

**Issue by fabledpig** [BME-MIT-IET/1505-iet-2019#7]
Néhány unit test megírása.

**Comment by Vikesz12** [comment]
![image](https://user-images.githubusercontent.com/24491701/57470902-475f6c00-728a-11e9-9b87-3fe912c79be9.png)
Mivel az aabb2 és a vec4 osztályokhoz nem készültek tesztek, ezért mi készítettük el azokat

**Comment by Vikesz12** [comment]
A teszteket a többihez hasnoló módon és hasonló helyen hoztuk létre egy új branchen(unit_test).

**Comment by ikazizzle** [comment]
![image](https://user-images.githubusercontent.com/36711974/57472280-5e538d80-728d-11e9-8d16-37506310c020.png)
A tesztek elkészültek, látható a változás a code coverageben is.

**Comment by micskeiz** [comment]
Megnéztem a repo-t, és nem túl sok a belerakott munka.

A házi feladat elfogadásához egészítsétek még kérlek ki a teszteket. Elég egy C fájlra koncentrálni, de ott érjetek el legalább 80%-os kódfedést (vagy indokoljátok, hogy ha ez valamiért nem megvalósítható, csak kevesebbel). A codecov coverage jelentés online változatát linkeljétek be a wikire, hogy ellenőrizhető legyen.

**Comment by micskeiz** [comment]
@fabledpig @Vikesz12 @ikazizzle

**Comment by Vikesz12** [comment]
![image](https://user-images.githubusercontent.com/24491701/58154009-def09180-7c70-11e9-85e8-15621314b3d5.png)
Mindegyikünk felvitte egy fájl lefedettségét 80% fölé. Az egyes jelentéseket pedig belinkeltük a wiki oldalra.

**Comment by micskeiz** [comment]
OK, így már rendben van a HF.
